name: Release snapshot

on:
  issue_comment:
    types: [created]

env:
  npm-token: ${{ secrets.NPM_TOKEN }}
  github-token: ${{ secrets.GITHUB_TOKEN }}
  node-version: '16.x'

jobs:
  deploy-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Acknowledge deployment request to commenter
        id: check
        uses: khan/pull-request-comment-trigger@v1.1.0
        with:
          trigger: '/release-snapshot'
          reaction: rocket
        env:
          GITHUB_TOKEN: ${{ env.github-token }}
      - name: Validate user
        if: ${{ steps.check.outputs.triggered == 'true' }}
        run: |
          if [[ "${AUTHOR_ASSOCIATION}" != 'OWNER' ]]
          then
            echo "User authorization failed"
            exit 1
          else
            echo "User authorization successful"
          fi
        env:
          AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}
      - name: check outputs
        run: echo ${{ steps.check.outputs.triggered }}

    outputs:
      triggered: ${{ steps.check.outputs.triggered }}

  deploy:
    runs-on: ubuntu-22.04
    needs: deploy-check
    if: needs.deploy-check.outputs.triggered == 'true'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: Configure NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ env.npm-token }}

      - name: Deploy snapshot
        run: |
          yarn changeset version --snapshot pr${{ github.event.issue.number }}
          yarn nx run-many --target=build
          yarn changeset publish --tag pr${{ github.event.issue.number }} --no-git-tag
        env:
          GITHUB_TOKEN: ${{ env.github-token }}
